### ISSUE TITLE
g0v news CORS issue

### ISSUE THREAD

**Issue by SeanGau** [g0v/landing-page#24]
g0v.news 放置在 medium，目前是抓 rss feed 但會遇到 cors 的問題導致無法顯示

![image](https://user-images.githubusercontent.com/12148555/157004874-7a6a9244-2377-4e6b-b12b-a8447168cedf.png)

**Comment by assanges** [comment]
跨域名資源的問題最終可能要透過自架PROXY來達成

SO：[How To Call Medium RSS Feed](https://stackoverflow.com/a/44469188) 
answered by [sideshowbarker](https://stackoverflow.com/users/441757/sideshowbarker) CC-BY-SA 3.0

* [CORS Anywhere (github)](https://github.com/Rob--W/cors-anywhere/)
* [Allow Origin (github)](https://github.com/Eiledon/alloworigin) / [(Live)](https://allorigins.win/)

**Comment by ronnywang** [comment]
因為揪松這邊目前在處理 g0v 媒體露出收集，我這邊有做一個針對一些 spreadsheet 的 cors proxy ，我也順手加上 g0v rss feed 好了

可以用 https://cors.g0v.ronny.tw/g0vrss.php 這個網址

**Comment by SeanGau** [comment]
大感謝Ronny！我就直接做修改了
