### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by kaizumaki** [g0v/landing-page#7]
I would like to translate the g0v website into Japanese.
https://github.com/g0v/landing-page/tree/i18n/web/locales
I should just create a directory named `ja` here, right?

**Comment by SeanGau** [comment]
Yes, then add "ja" into config file
https://github.com/g0v/landing-page/blob/i18n/web/config.json

**Comment by kaizumaki** [comment]
@SeanGau Thanks for your response! I will do so.

I would like to assemble a team to do the translation and review into Japanese. I think it will take some time.

**Comment by SeanGau** [comment]
Thanks for all the contributions! I just do a merge to i18n branch after some fix to avoid more key missing.

**Comment by kaizumaki** [comment]
@SeanGau Thanks for merging my repository! I and my friends will review the Japanese part the day after tomorrow. After fixing it, I will send a pull request!

**Comment by kaizumaki** [comment]
I've also changed the manifest to Japanese in #18 . So, I'd like to close this issue.
